name = "GPU_simulation"
version = "0.1.0"
license = "license"
author = "MrTired"
maintainer = "yu-ma31@i.softbank.jp"
copyright = "Copyright 2023, MrTired"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

