name = "GPU_simulation"
version = "0.1.0"
license = "license"
author = "osada-yum"
maintainer = "osada.yum@gmail.com"
copyright = "Copyright 2023, osada-yum"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
external-modules = ["cudafor", "curand"]
[dependencies]
numeric_simulation = { git = "https://github.com/osada-yum/Numerical_utilities.git" }
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[executable]]
name = "ising2d_gpu_relaxation"
source-dir = "app"
main = "ising2d_gpu_relaxation.f90"
[[executable]]
name = "ising3d_gpu_relaxation"
source-dir = "app"
main = "ising3d_gpu_relaxation.f90"
[[executable]]
name = "xy2d_gpu_relaxation"
source-dir = "app"
main = "xy2d_gpu_relaxation.f90"
[[executable]]
name = "clock_gpu_relaxation"
source-dir = "app"
main = "clock_gpu_relaxation.f90"
[[executable]]
name = "clock_gpu_multi_relaxation"
source-dir = "app"
main = "clock_gpu_multi_relaxation.f90"
